// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ideeenbus.Repository;

#nullable disable

namespace ideeenbus.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250406130645_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CategorieEntityIdeeEntity", b =>
                {
                    b.Property<int>("CategoryEntitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdeeEntitiesId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryEntitiesId", "IdeeEntitiesId");

                    b.HasIndex("IdeeEntitiesId");

                    b.ToTable("CategorieEntityIdeeEntity");
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.CategorieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.CategoryInIdeeEntity", b =>
                {
                    b.Property<int>("CategoryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdeeEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdeeEntityId1")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryEntityId", "IdeeEntityId");

                    b.HasIndex("CategorieEntityId");

                    b.HasIndex("IdeeEntityId1");

                    b.ToTable("CategorieInIdeeEntities");
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.IdeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BeginDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Onderwerp")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ideeen");
                });

            modelBuilder.Entity("CategorieEntityIdeeEntity", b =>
                {
                    b.HasOne("ideeenbus.Service.Entity.CategorieEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ideeenbus.Service.Entity.IdeeEntity", null)
                        .WithMany()
                        .HasForeignKey("IdeeEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.CategoryInIdeeEntity", b =>
                {
                    b.HasOne("ideeenbus.Service.Entity.CategorieEntity", "CategorieEntity")
                        .WithMany("CategoryInIdeeEntities")
                        .HasForeignKey("CategorieEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ideeenbus.Service.Entity.IdeeEntity", "IdeeEntity")
                        .WithMany("CategoryInIdeeEntities")
                        .HasForeignKey("IdeeEntityId1");

                    b.Navigation("CategorieEntity");

                    b.Navigation("IdeeEntity");
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.CategorieEntity", b =>
                {
                    b.Navigation("CategoryInIdeeEntities");
                });

            modelBuilder.Entity("ideeenbus.Service.Entity.IdeeEntity", b =>
                {
                    b.Navigation("CategoryInIdeeEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
