// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ideeenbus.Service;

#nullable disable

namespace ideeenbus.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CategorieEntityIdeeEntity", b =>
                {
                    b.Property<int>("categoryEntitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ideeEntitiesId")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryEntitiesId", "ideeEntitiesId");

                    b.HasIndex("ideeEntitiesId");

                    b.ToTable("CategorieEntityIdeeEntity");
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.CategorieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.CategoryInIdeeEntity", b =>
                {
                    b.Property<int>("CategoryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdeeEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdeeEntityId1")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryEntityId", "IdeeEntityId");

                    b.HasIndex("CategorieEntityId");

                    b.HasIndex("IdeeEntityId1");

                    b.ToTable("CategorieInIdeeEntities");
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.IdeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("beginDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("onderwerp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ideeen");
                });

            modelBuilder.Entity("CategorieEntityIdeeEntity", b =>
                {
                    b.HasOne("ideeenbus.Service.Dao.CategorieEntity", null)
                        .WithMany()
                        .HasForeignKey("categoryEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ideeenbus.Service.Dao.IdeeEntity", null)
                        .WithMany()
                        .HasForeignKey("ideeEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.CategoryInIdeeEntity", b =>
                {
                    b.HasOne("ideeenbus.Service.Dao.CategorieEntity", "CategorieEntity")
                        .WithMany("categoryInIdeeEntities")
                        .HasForeignKey("CategorieEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ideeenbus.Service.Dao.IdeeEntity", "IdeeEntity")
                        .WithMany("categoryInIdeeEntities")
                        .HasForeignKey("IdeeEntityId1");

                    b.Navigation("CategorieEntity");

                    b.Navigation("IdeeEntity");
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.CategorieEntity", b =>
                {
                    b.Navigation("categoryInIdeeEntities");
                });

            modelBuilder.Entity("ideeenbus.Service.Dao.IdeeEntity", b =>
                {
                    b.Navigation("categoryInIdeeEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
