// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ideeenbus.Service;

#nullable disable

namespace ideeenbus.Migrations
{
    [DbContext(typeof(IdeeEntityContext))]
    partial class IdeeEntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ideeenbus.Service.Dao.IdeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("beginDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("onderwerp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ideeen");
                });
#pragma warning restore 612, 618
        }
    }
}
